### ISSUE TITLE
recipe installs psutil 3.0

### ISSUE THREAD

**Issue by veloutin** [anybox/anybox.recipe.odoo#43]
**Workaround: pin psutil = 2.1.1 in [versions]**

This creates errors like this:

```
2015-06-15 17:29:38,128 6166 ERROR ? openerp.service.server: Worker (6166) Exception occured, exiting...
Traceback (most recent call last):
  File "/opt/odoo8/git/odoo/openerp/service/server.py", line 732, in run
    self.process_limit()
  File "/opt/odoo8/git/odoo/openerp/service/server.py", line 687, in process_limit
    rss, vms = psutil.Process(os.getpid()).get_memory_info()
AttributeError: 'Process' object has no attribute 'get_memory_info'
```

Because the API changed.

psutil is frozen at 2.1.1 in the odoo requirements.txt, the recipe should respect that.

**Comment by StefanRijnhart** [comment]
I was surprised too that the version from requirements.txt is not honoured. But I don't mind living on the edge ;-). BTW. fix in Odoo https://github.com/odoo/odoo/pull/7082

**Comment by veloutin** [comment]
Thanks for the fix!

This is still a bug that requirements.txt is not honoured. 

This opens up users to a lot of potential problems, with no benefit.

**Comment by StefanRijnhart** [comment]
@veloutin Agreed

**Comment by ccomb** [comment]
It might be a nice bonus to support the requirements.txt in the recipe itself, but actually there is an easy way to satisfy it today : just use another recipe dedicated to that: ``collective.recipe.pip``

Example buildout that should work with latest OCB 8.0 (with pychart problem solved) :

```
[buildout]
parts = pip odoo
versions = versions

[odoo]
recipe = anybox.recipe.odoo:server
version = git http://github.com/OCA/odoo.git odoo 8.0 depth=1

[pip]
recipe = collective.recipe.pip
configs = parts/odoo/requirements.txt
versions = versions

[versions]
collective.recipe.pip = 0.2.0
```
I've tried with the latest version 0.3.1 of the pip recipe, but I had to use an older one.

**Comment by lmignon** [comment]
@ccomb I'm curious to see if that works on a fresh install. `Parts` are executed in the order they are declared. (pip and after odoo) therefore, when pip is executed, the sources of Odoo are not yet available. Am I wrong?

**Comment by StefanRijnhart** [comment]
@ccomb thank you for your answer. But @lmignon is right. It does not work if the odoo part has not yet bin checked out.

```
InstallationError: Could not open requirements file: [Errno 2] No such file or directory: '/home/user/git/buildout/parts/odoo/requirements.txt'
```

**Comment by ccomb** [comment]
You're right, so instead of a local file we can use an URL:
```configs = https://raw.githubusercontent.com/OCA/OCB/8.0/requirements.txt```
I've updated the comment above

**Comment by ccomb** [comment]
After trying very quickly it seems that the versions of the requirements.txt are ignored by the odoo recipe, although the pip recipe seems to correcly set them in the versions section. Needs more investigation...

**Comment by gracinet** [comment]
Hi, and sorry to be slow, I'm currently out of the office.
 I'm quite favorable that the recipe could use Odoo's requirements.txt, if existing, even though that's a bit redundant with buildout's native system for that (using a versions section).

I also like choice, so what should be the implicit behaviour ?

1) follow requirements.txt by default, but this is a change in default behaviour.
2) follow requirements.txt only if a certain option is present.

It's not (very) complicated to support on the technical side of things, considering that we even had in the past to go as far as to patch OpenERP's setup.py on the fly (it's thankfully cleaner now).

In scenario 1, we'd keep an option to disable it anyway, because if noone ever tries new distributions, that's also bad, and Stefan is on the adventurous side :-)

I'll be back to work on June 29th, with a greeeat pile of stuff to be done for the recipe.

It's not probably the right place to do it, but I think giving commit rights to more people will be considered at that time, me being either flooded with other stuff or plainly not working.

**Comment by gracinet** [comment]
Oh just forgot to say : in my mind, `versions` and `develop` options would have precedence over the  the requirements.txt.

**Comment by lmignon** [comment]
@gracinet :+1:

**Comment by StefanRijnhart** [comment]
Thanks @gracinet. I'd say follow requirements.txt only if a certain option is present, precisely for the argument of letting newer versions be tested. And with versions and develop options taking precedence.

**Comment by gracinet** [comment]
@StefanRijnhart @lmignon : thanks for your votes, now working on implementation.
I'll try not to create a dependency to pip, because that can be problematic, but we'll see.

**Comment by lmignon** [comment]
@gracinet Thank you for the feedback and to take care of this problem!

**Comment by gracinet** [comment]
Got a working implementation (not ready for merge): https://github.com/gracinet/anybox.recipe.odoo/commit/2b10027a053a343ff5ada7f35047f6b4d3e99348

Writing tests for this is going to be tough, and somewhat limited, but it must be done, because that's introducing new dependencies on buildout internals

**Comment by gracinet** [comment]
A side node, to try this, I have currently to supersede the requirements file's `reportlab==3.1.8` with `3.2.0`, otherwise I get a version conflict that buildout can't resolve by itself.

**Comment by lmignon** [comment]
@gracinet I've not yet tested your changes nevertheless your changes seem good and well structured on first read. Thank you!

**Comment by ccomb** [comment]
I've contributed a fix in collective.recipe.pip for older pip https://pypi.python.org/pypi/collective.recipe.pip/0.3.2
And in the example buildout above, there is one thing missing in the [odoo] section:
```eggs = ${pip:eggs}```

I've updated the comment with the example, and the requirements.txt is now correctly used.

Now I get the same version conflict as @gracinet :( : 
```We already have: Pillow 2.5.1
but reportlab 3.1.8 requires 'pillow==2.0.0,>=2.4.0'.```

Looks like a bug in buildout.easy_install

**Comment by ccomb** [comment]
Here is the bug report regarding the version conflict https://bitbucket.org/rptlab/reportlab/issues/55/setuptools-80-cannot-install-reportlab-318

I've done a PR for odoo: odoo/odoo#7630 and for OCB: OCA/OCB#280 to switch to 3.1.44 instead:

**Comment by lmignon** [comment]
Fixed 2dda99b8b0c440e7dfda835f5bbe4ff2448a0a8a

**Comment by gracinet** [comment]
I confirm that the hack of using a separate `collective.recipe.pip` is to be avoided. Two reasons:

- doesn't let you override a version (tried a few combinations), and that impairs upgrading the surrounding OS version (older Pillow have compilation issues on recent distros)
- if you're using freeze/extract you're probably out of luck

**Comment by ccomb** [comment]
Sure, that was a hack while waiting for the recipe to directly support requirements.txt.
